// Android Event Constants
export const TRUECALLER_ANDROID_EVENTS = {
  SUCCESS: 'TruecallerAndroidSuccess',
  FAILURE: 'TruecallerAndroidFailure',
};

// iOS Event Constants
export const TRUECALLER_IOS_EVENTS = {
  SUCCESS: 'TruecallerIOSSuccess',
  FAILURE: 'TruecallerIOSFailure',
};

// Button Text Customizations for Android
export const TRUECALLER_ANDROID_CUSTOMIZATIONS = {
  BUTTON_TEXTS: {
    CONTINUE: 'TRUECALLER_ANDROID_BUTTON_TEXT_CONTINUE',
    ACCEPT: 'TRUECALLER_ANDROID_BUTTON_TEXT_ACCEPT',
    CONFIRM: 'TRUECALLER_ANDROID_BUTTON_TEXT_CONFIRM',
    PROCEED: 'TRUECALLER_ANDROID_BUTTON_TEXT_PROCEED',
  },
  BUTTON_SHAPES: {
    ROUNDED: 'TRUECALLER_ANDROID_BUTTON_SHAPE_ROUNDED',
    RECTANGLE: 'TRUECALLER_ANDROID_BUTTON_SHAPE_RECTANGLE',
  },
  FOOTER_TEXTS: {
    SKIP: 'TRUECALLER_ANDROID_FOOTER_BUTTON_SKIP',
    ANOTHER_MOBILE_NUMBER:
      'TRUECALLER_ANDROID_FOOTER_BUTTON_ANOTHER_MOBILE_NUMBER',
    ANOTHER_METHOD: 'TRUECALLER_ANDROID_FOOTER_BUTTON_ANOTHER_METHOD',
    MANUALLY: 'TRUECALLER_ANDROID_FOOTER_BUTTON_MANUALLY',
    LATER: 'TRUECALLER_ANDROID_FOOTER_BUTTON_LATER',
  },
  CONSENT_HEADINGS: {
    LOG_IN_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_LOG_IN_TO',
    SIGN_UP_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_SIGN_UP_WITH',
    SIGN_IN_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_SIGN_IN_TO',
    VERIFY_NUMBER_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_NUMBER_WITH',
    REGISTER_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_REGISTER_WITH',
    GET_STARTED_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_GET_STARTED_WITH',
    PROCEED_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_PROCEED_WITH',
    VERIFY_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_WITH',
    VERIFY_PROFILE_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_PROFILE_WITH',
    VERIFY_YOUR_PROFILE_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_YOUR_PROFILE_WITH',
    VERIFY_PHONE_NO_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_PHONE_NO_WITH',
    VERIFY_YOUR_NO_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_VERIFY_YOUR_NO_WITH',
    CONTINUE_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_CONTINUE_WITH',
    COMPLETE_ORDER_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_COMPLETE_ORDER_WITH',
    PLACE_ORDER_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_PLACE_ORDER_WITH',
    COMPLETE_BOOKING_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_COMPLETE_BOOKING_WITH',
    CHECKOUT_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_CHECKOUT_WITH',
    MANAGE_DETAILS_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_MANAGE_DETAILS_WITH',
    MANAGE_YOUR_DETAILS_WITH:
      'TRUECALLER_ANDROID_CONSENT_HEADING_MANAGE_YOUR_DETAILS_WITH',
    LOGIN_TO_WITH_ONE_TAP:
      'TRUECALLER_ANDROID_CONSENT_HEADING_LOGIN_TO_WITH_ONE_TAP',
    SUBSCRIBE_TO: 'TRUECALLER_ANDROID_CONSENT_HEADING_SUBSCRIBE_TO',
    GET_UPDATES_FROM: 'TRUECALLER_ANDROID_CONSENT_HEADING_GET_UPDATES_FROM',
    CONTINUE_READING_ON:
      'TRUECALLER_ANDROID_CONSENT_HEADING_CONTINUE_READING_ON',
    GET_NEW_UPDATES_FROM:
      'TRUECALLER_ANDROID_CONSENT_HEADING_GET_NEW_UPDATES_FROM',
    LOGIN_SIGNUP_WITH: 'TRUECALLER_ANDROID_CONSENT_HEADING_LOGIN_SIGNUP_WITH',
  },
};

// Additional Constants for Supported Languages
export const TRUECALLER_LANGUAGES = {
  ENGLISH: 'en',
  HINDI: 'hi',
  MARATHI: 'mr',
  TELUGU: 'te',
  MALAYALAM: 'ml',
  URDU: 'ur',
  PUNJABI: 'pa',
  TAMIL: 'ta',
  BENGALI: 'bn',
  KANNADA: 'kn',
  SWAHILI: 'sw',
  ARABIC: 'ar',
};

export const TRUECALLER_API_URLS = {
  TOKEN_URL: 'https://oauth-account-noneu.truecaller.com/v1/token',
  USER_INFO_URL: 'https://oauth-account-noneu.truecaller.com/v1/userinfo',
};

export const DEFAULT_BUTTON_TEXT_COLOR = '#FFFFFF';
export const DEFAULT_BUTTON_COLOR = '#2C765CFF';
export const DEFAULT_BUTTON_TEXT =
  TRUECALLER_ANDROID_CUSTOMIZATIONS.BUTTON_TEXTS.ACCEPT;
export const DEFAULT_BUTTON_SHAPE =
  TRUECALLER_ANDROID_CUSTOMIZATIONS.BUTTON_SHAPES.ROUNDED;
export const DEFAULT_FOOTER_BUTTON_TEXT =
  TRUECALLER_ANDROID_CUSTOMIZATIONS.FOOTER_TEXTS.ANOTHER_METHOD;
export const DEFAULT_CONSENT_HEADING =
  TRUECALLER_ANDROID_CUSTOMIZATIONS.CONSENT_HEADINGS.SIGN_UP_WITH;
